export enum L1RuntimeStatus {
  PROVISIONING = "PROVISIONING",
  ACTIVE = "ACTIVE",
  IDLE = "IDLE",
  CHECKPOINTING = "CHECKPOINTING",
  CHECKPOINT_FAILED = "CHECKPOINT_FAILED",
  UNLOADING = "UNLOADING",
  UNLOAD_FAILED = "UNLOAD_FAILED",
  UNLOADED = "UNLOADED",
  FAILED = "FAILED",
}

export enum L2TaskStatus {
  QUEUED = "QUEUED",
  SPAWNING = "SPAWNING",
  RUNNING = "RUNNING",
  WAITING_INPUT = "WAITING_INPUT",
  COMPLETED = "COMPLETED",
  FAILED = "FAILED",
  CHECKPOINTED = "CHECKPOINTED",
  UNLOADED = "UNLOADED",
}

export enum AgentLevel {
  L1 = "L1",
  L2 = "L2",
}

export enum TraceEventType {
  REQUEST_ACCEPTED = "REQUEST_ACCEPTED",
  L1_ENSURE_STARTED = "L1_ENSURE_STARTED",
  L1_PROFILE_CREATED = "L1_PROFILE_CREATED",
  L1_PROFILE_REUSED = "L1_PROFILE_REUSED",
  L1_RESTORED = "L1_RESTORED",
  L2_SPAWN_REQUESTED = "L2_SPAWN_REQUESTED",
  L2_SPAWNED = "L2_SPAWNED",
  SKILL_SELECTED = "SKILL_SELECTED",
  EXECUTION_CONTEXT_CREATED = "EXECUTION_CONTEXT_CREATED",
  TOOL_CALL_REQUESTED = "TOOL_CALL_REQUESTED",
  TOOL_CALL_ALLOWED = "TOOL_CALL_ALLOWED",
  TOOL_CALL_DENIED = "TOOL_CALL_DENIED",
  TOOL_CALL_COMPLETED = "TOOL_CALL_COMPLETED",
  MEMORY_READ = "MEMORY_READ",
  MEMORY_WRITE = "MEMORY_WRITE",
  CHECKPOINT_STARTED = "CHECKPOINT_STARTED",
  CHECKPOINT_COMPLETED = "CHECKPOINT_COMPLETED",
  CHECKPOINT_FAILED = "CHECKPOINT_FAILED",
  L2_UNLOADED = "L2_UNLOADED",
  L1_UNLOAD_STARTED = "L1_UNLOAD_STARTED",
  L1_UNLOADED = "L1_UNLOADED",
  RESTORE_STARTED = "RESTORE_STARTED",
  RESTORE_COMPLETED = "RESTORE_COMPLETED",
  CAPABILITY_PROFILE_CHANGED = "CAPABILITY_PROFILE_CHANGED",
}
